config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-firebrick-uakari.sh
        container: qc.acc_scummy-russet-frise
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-alizarin-sloth.sh
        container: qc.doc_messy-razzmatazz-buzzard
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-sepia-woodpecker.sh
        container: qc.doc_pasty-rose-leopard
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-seashell-cougar.sh
        container: qc.lic_flaky-flax-spaniel
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-amaranth-stoat.sh
        container: qc.met_leaky-lilac-anteater
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-peach-meerkat.sh
        container: qc.sec_flabby-bistre-snail
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-crimson-mau.sh
        container: qc.sty_baggy-orchid-ocelot
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-cardinal-yak.sh
        container: qc.ver_skinny-magnolia-skunk
timeout: 600
