config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-white-bordeaux.sh
        container: qc.acc_frumpy-jade-beagle
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-eggplant-pig.sh
        container: qc.doc_woolly-indigo-blue
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-taupe-gar.sh
        container: qc.doc_stuffy-lime-harrier
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-ultramarine-shrew.sh
        container: qc.lic_slimy-salmon-greyhound
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-rose-kiwi.sh
        container: qc.met_blurry-silver-budgerigar
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ochre-lemming.sh
        container: qc.sec_pasty-cyan-shark
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-heliotrope-paradise.sh
        container: qc.sty_stuffy-yellow-clam
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-jade-eleuth.sh
        container: qc.ver_lumpy-turquoise-badger
timeout: 600
