config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-buff-lion.sh
        container: qc.acc_baggy-firebrick-stingray
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-russet-chihuahua.sh
        container: qc.doc_cranky-buff-anteater
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-plum-zorse.sh
        container: qc.doc_sunny-magnolia-akita
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-grey-bombay.sh
        container: qc.lic_clammy-sangria-binturong
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-periwinkle-vulture.sh
        container: qc.met_snazzy-cerulean-balinese
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-rose-rottweiler.sh
        container: qc.sec_crabby-asparagus-oyster
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-indigo-falcon.sh
        container: qc.sty_boozy-taupe-ibis
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tomato-meerkat.sh
        container: qc.ver_silly-amethyst-cheetah
timeout: 600
