config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-sapphire-sheepdog.sh
        container: qc.acc_jumpy-plum-bracke
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-tan-robin.sh
        container: qc.doc_ready-ochre-flamingo
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-salmon-insect.sh
        container: qc.doc_gloppy-buff-orangutan
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-buff-cuttlefish.sh
        container: qc.lic_chummy-peach-gar
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-auburn-akbash.sh
        container: qc.met_shaggy-brass-liger
timeout: 600
