config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-tomato-rabbit.sh
        container: qc.acc_grumpy-tangerine-capybara
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-aquamarine-chamois.sh
        container: qc.doc_wiggy-goldenrod-quoll
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-tangerine-cuscus.sh
        container: qc.doc_dorky-brown-monkey
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-aquamarine-donkey.sh
        container: qc.lic_squeaky-chocolate-iguana
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-brass-booby.sh
        container: qc.met_nerdy-lilac-millipede
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-cinnamon-flounder.sh
        container: qc.sec_snippy-indigo-gibbon
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-orange-birman.sh
        container: qc.sty_skinny-peach-civet
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-green-emu.sh
        container: qc.ver_snippy-amethyst-rattlesnake
timeout: 600
