config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-ivory-indri.sh
        container: qc.acc_cloudy-denim-salamander
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-denim-quoll.sh
        container: qc.doc_seedy-malachite-dragon
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-magnolia-capuchin.sh
        container: qc.doc_whiny-olive-badger
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-celadon-hyena.sh
        container: qc.lic_foggy-ultramarine-dragonfly
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-grey-slug.sh
        container: qc.met_wimpy-red-mastiff
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-taupe-kingfisher.sh
        container: qc.sec_scaly-lavender-bison
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-bronze-burmese.sh
        container: qc.sty_nerdy-tan-bandicoot
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-yellow-bison.sh
        container: qc.ver_lumpy-indigo-abyssinian
timeout: 600
