config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-alpha5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-asparagus-ant.sh
        container: qc.acc_woozy-pumpkin-crane
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-khaki-paradise.sh
        container: qc.doc_seedy-crimson-lionfish
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-mustard-turkey.sh
        container: qc.doc_flabby-burgundy-mongrel
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-smalt-harrier.sh
        container: qc.lic_sloppy-turquoise-frigatebird
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-indigo-neanderthal.sh
        container: qc.met_goopy-cinnamon-lemur
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-sepia-quoll.sh
        container: qc.sec_goopy-chestnut-fish
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-myrtle-macaque.sh
        container: qc.sty_muggy-taupe-harrier
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server is_semver.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-rose-molly.sh
        container: qc.ver_seedy-vermilion-rattlesnake
timeout: 600
