config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-emerald-bird.sh
        container: qc.acc_fuzzy-ruby-termite
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-carmine-wolf.sh
        container: qc.doc_sleazy-russet-jaguar
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-corn-mayfly.sh
        container: qc.doc_randy-saffron-rabbit
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cyan-fousek.sh
        container: qc.lic_silly-olivine-neanderthal
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-emerald-bordeaux.sh
        container: qc.met_foggy-sangria-gerbil
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-myrtle-otter.sh
        container: qc.sec_jumpy-rust-panda
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-azure-husky.sh
        container: qc.sty_bumpy-brass-hyrax
timeout: 600
