config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0-alpha2
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/masterdatascience-UIMP-UC/predictaas-api-server:
      branch: master
      repo: https://github.com/masterdatascience-UIMP-UC/predictaas-api-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-auburn-wolfhound.sh
        container: qc.acc_bumpy-ruby-jaguar
  QC.Doc:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-russet-chow.sh
        container: qc.doc_hasty-gold-beagle
      github.com/masterdatascience-UIMP-UC/predictaas-api-server git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-beige-wasp.sh
        container: qc.doc_sleazy-russet-markhor
      github.com/masterdatascience-UIMP-UC/predictaas-api-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-ultramarine-mule.sh
        container: qc.doc_pasty-brown-eleuth
  QC.FAIR:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-teal-javanese.sh
        container: qc.fair_sleepy-puce-affenpinscher
  QC.Lic:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-carmine-flamingo.sh
        container: qc.lic_chummy-razzmatazz-grouse
  QC.Met:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-seashell-squid.sh
        container: qc.met_lumpy-myrtle-tarantula
  QC.Sec:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-gamboge-molly.sh
        container: qc.sec_boozy-wisteria-iguana
  QC.Sty:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ultramarine-alligator.sh
        container: qc.sty_shaky-silver-bullfrog
  QC.Ver:
    repos:
      github.com/masterdatascience-UIMP-UC/predictaas-api-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-bistre-baboon.sh
        container: qc.ver_pokey-tan-zorse
timeout: 1800
